" Specify a directory for plugins
" - For Neovim: ~/.local/share/nvim/plugged
" - Avoid using standard Vim directory names like 'plugin'

" call plug#begin('~/.local/share/nvim/plugged')
"
" " Toggle comments
" " Plug 'preservim/nerdcommenter'
"
" call plug#end()


syntax on
filetype indent on

" TODO: What this does?
set smartindent
set autoindent

" show existing tab with 2 spaces width
set tabstop=2
set softtabstop=2
set shiftwidth=2

" Convert tabs to spaces
set expandtab

" Copying to clipboard
vnoremap <C-c> "*y
